In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
covid = pd.read_csv("compact.csv", sep=None, engine='python')
covid.shape
covid.loc[:100]

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,...,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,human_development_index
0,Afghanistan,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
1,Afghanistan,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
2,Afghanistan,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
3,Afghanistan,2020-01-04,0.0,0.0,NaN,0.000000,0.000000,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
4,Afghanistan,2020-01-05,0.0,0.0,NaN,0.000000,0.000000,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Afghanistan,2020-04-06,299.0,25.0,27.571428,7.368371,0.616085,0.679453,7.0,2.0,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
97,Afghanistan,2020-04-07,337.0,38.0,31.857143,8.304819,0.936449,0.785068,7.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
98,Afghanistan,2020-04-08,367.0,30.0,28.714285,9.044121,0.739301,0.707617,11.0,4.0,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
99,Afghanistan,2020-04-09,423.0,56.0,33.000000,10.424150,1.380029,0.813232,14.0,3.0,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
100,Afghanistan,2020-04-10,444.0,21.0,35.714287,10.941661,0.517511,0.880121,15.0,1.0,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN

In [23]:
 covid.isnull().sum()

country                            0
date                               0
total_cases                    12348
new_cases                      16288
new_cases_smoothed             17497
                               ...
extreme_poverty               204429
diabetes_prevalence            90733
handwashing_facilities        293379
hospital_beds_per_thousand    182269
human_development_index       570606
Length: 61, dtype: int64

In [24]:
covid.dropna(how="all")

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,...,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,human_development_index
0,Afghanistan,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
1,Afghanistan,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
2,Afghanistan,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
3,Afghanistan,2020-01-04,0.0,0.0,NaN,0.000,0.0,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
4,Afghanistan,2020-01-05,0.0,0.0,NaN,0.000,0.0,NaN,0.0,0.0,...,40578847.0,62.215549,16.752001,65.616997,1983.812622,NaN,11.7,51.938343,0.35,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570601,Zimbabwe,2026-02-18,266436.0,0.0,0.0,16580.682,0.0,0.0,5740.0,0.0,...,16069061.0,41.538223,17.683001,62.360100,5215.252930,49.219894,1.5,42.509991,1.95,NaN
570602,Zimbabwe,2026-02-19,266436.0,0.0,0.0,16580.682,0.0,0.0,5740.0,0.0,...,16069061.0,41.538223,17.683001,62.360100,5215.252930,49.219894,1.5,42.509991,1.95,NaN
570603,Zimbabwe,2026-02-20,266436.0,0.0,0.0,16580.682,0.0,0.0,5740.0,0.0,...,16069061.0,41.538223,17.683001,62.360100,5215.252930,49.219894,1.5,42.509991,1.95,NaN
570604,Zimbabwe,2026-02-21,266436.0,0.0,0.0,16580.682,0.0,0.0,5740.0,0.0,...,16069061.0,41.538223,17.683001,62.360100,5215.252930,49.219894,1.5,42.509991,1.95,NaN
570605,Zimbabwe,2026-02-22,266436.0,0.0,0.0,16580.682,0.0,0.0,5740.0,0.0,...,16069061.0,41.538223,17.683001,62.360100,5215.252930,49.219894,1.5,42.509991,1.95,NaN

In [25]:
covid.columns.tolist()

['country',
 'date',
 'total_cases',
 'new_cases',
 'new_cases_smoothed',
 'total_cases_per_million',
 'new_cases_per_million',
 'new_cases_smoothed_per_million',
 'total_deaths',
 'new_deaths',
 'new_deaths_smoothed',
 'total_deaths_per_million',
 'new_deaths_per_million',
 'new_deaths_smoothed_per_million',
 'excess_mortality',
 'excess_mortality_cumulative',
 'excess_mortality_cumulative_absolute',
 'excess_mortality_cumulative_per_million',
 'hosp_patients',
 'hosp_patients_per_million',
 'weekly_hosp_admissions',
 'weekly_hosp_admissions_per_million',
 'icu_patients',
 'icu_patients_per_million',
 'weekly_icu_admissions',
 'weekly_icu_admissions_per_million',
 'stringency_index',
 'reproduction_rate',
 'total_tests',
 'new_tests',
 'total_tests_per_thousand',
 'new_tests_per_thousand',
 'new_tests_smoothed',
 'new_tests_smoothed_per_thousand',
 'positive_rate',
 'tests_per_case',
 'total_vaccinations',
 'people_vaccinated',
 'people_fully_vaccinated',
 'total_boosters',
 'new_vaccinations',
 'new_vaccinations_smoothed',
 'total_vaccinations_per_hundred',
 'people_vaccinated_per_hundred',
 'people_fully_vaccinated_per_hundred',
 'total_boosters_per_hundred',
 'new_vaccinations_smoothed_per_million',
 'new_people_vaccinated_smoothed',
 'new_people_vaccinated_smoothed_per_hundred',
 'code',
 'continent',
 'population',
 'population_density',
 'median_age',
 'life_expectancy',
 'gdp_per_capita',
 'extreme_poverty',
 'diabetes_prevalence',
 'handwashing_facilities',
 'hospital_beds_per_thousand',
 'human_development_index']

In [28]:
covid.drop(columns=[ 'new_deaths_per_million',
 'new_deaths_smoothed_per_million',
 'excess_mortality',
 'excess_mortality_cumulative',
 'excess_mortality_cumulative_absolute',
 'excess_mortality_cumulative_per_million',
 'hosp_patients',
 'hosp_patients_per_million',
 'weekly_hosp_admissions',
 'weekly_hosp_admissions_per_million',
 'icu_patients',
 'icu_patients_per_million','weekly_icu_admissions_per_million',
 'stringency_index',
 'reproduction_rate',
 'total_tests',
 'new_tests',
 'total_tests_per_thousand',
 'new_tests_per_thousand',
 'new_tests_smoothed',
 'new_tests_smoothed_per_thousand',
 'positive_rate',
 'tests_per_case',
 'total_vaccinations',
 'people_vaccinated',
 'people_fully_vaccinated',
 'total_boosters',
 'new_vaccinations',
 'new_vaccinations_smoothed',
 'total_vaccinations_per_hundred',
 'people_vaccinated_per_hundred',
 'people_fully_vaccinated_per_hundred',
 'total_boosters_per_hundred',
 'new_vaccinations_smoothed_per_million',
 'new_people_vaccinated_smoothed',
 'new_people_vaccinated_smoothed_per_hundred',], inplace=True)

In [29]:
covid.columns.tolist()

['country',
 'date',
 'total_cases',
 'new_cases',
 'new_cases_smoothed',
 'total_cases_per_million',
 'new_cases_per_million',
 'new_cases_smoothed_per_million',
 'total_deaths',
 'new_deaths',
 'new_deaths_smoothed',
 'total_deaths_per_million',
 'weekly_icu_admissions',
 'code',
 'continent',
 'population',
 'population_density',
 'median_age',
 'life_expectancy',
 'gdp_per_capita',
 'extreme_poverty',
 'diabetes_prevalence',
 'handwashing_facilities',
 'hospital_beds_per_thousand',
 'human_development_index']

In [30]:
covid.drop(columns=['weekly_icu_admissions', 'new_deaths_smoothed', 'new_cases_per_million',
 'new_cases_smoothed_per_million', 'new_cases_smoothed'],inplace=True)

In [31]:
covid.columns.tolist()

['country',
 'date',
 'total_cases',
 'new_cases',
 'total_cases_per_million',
 'total_deaths',
 'new_deaths',
 'total_deaths_per_million',
 'code',
 'continent',
 'population',
 'population_density',
 'median_age',
 'life_expectancy',
 'gdp_per_capita',
 'extreme_poverty',
 'diabetes_prevalence',
 'handwashing_facilities',
 'hospital_beds_per_thousand',
 'human_development_index']

In [56]:
a = covid.groupby(["continent"]).sum()
col = a.index.tolist()
def drop_continents_from_country_column(rows):
    if rows["country"] in col:
        rows.drop(index=rows["country"],axis="index")
    return rows["country"]

rows["country"] = covid.apply(drop_continents_from_country_column,axis="columns")

Africa

KeyError: "['Africa'] not found in axis"